# Development environment for Hashi@Home deployment.
[settings]
auto_install = true

[env]
_.python.venv = {path = ".venv", create = true }
INTERPRETER_PYTHON_FALLBACK="/usr/bin/python3 "

[tools]
prek = "0.4.8"
terraform = "1.15.7"
trivy = "0.72.0"
python = "3.13"
uv = "0.11.28"

[tasks.deps]
description = "Install dependencies"
run = "uv pip install -r requirements.txt"

[tasks.collections]
depends = ["deps"]
description = "Install collections"
run = "ansible-galaxy install -f -r requirements.yml"
