consul_servers:
  hosts:
    bare:
    ticklish:
    inky:
consul_agents:
  children:
    pi3s:
    pi4s:
    pi5s:
    pizeros:
    compute_pis:
    minipcs:
  vars:
    consul_version_ceiling:
      armv6l: 1.17.1
      aarch64:
      x86_64:
    consul_template_version: 0.29.6
